dist: xenial
language: go

go:
  - 1.9

branches:
  only:
  - master
#  - sdlOnly

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsdl2-dev

install:
  - go get github.com/kjx98/golib/to

script:
  - cd sdl
  - go build
